[homes]
	
   comment = %U's Home directory 
   path = /home/%U
   browseable = no
   read only = no
   create mode = 0750
#	recycle bin = /samba/muell/%U

# The following share gives all users access to the Server's CD drive,
# assuming it is mounted under /cd. To enable this share, please remove
# the semicolons before the lines
#
# [cdrom]
#   comment = Linux CD-ROM
#   path = /cdrom
#   read only = yes
#   locking = no

[print$]
   path = /samba/reiser/printers
   guest ok = yes
   browseable = yes
   read only = yes
   write list = @"Domain Admins", @"Print Operators", @"Administrators", root, Administrator

[printers]
   directory = /samba/reiser/printspool
   comment = All Printers
   browseable = no
   printable = yes
   public = no
   read only = yes
   create mode = 0700
   write list = @"Domain Admins", @"Print Operators", @"Administrators", root, Administrator

# the pdc-relevant shares

[netlogon]
	comment = The NETLOGON share
   browseable = yes
   writeable = no
   path = /samba/reiser/netlogon
   write list = @"Domain Admins", @"Print Operators", @"Administrators", root, Administrator
   nt acl support = no

[profiles]
	comment = The PROFILES share
   browseable = yes
   writeable = yes
   path = /samba/reiser/profiles
   create mask = 0600
   directory mask = 0700
   nt acl support = no


# and here your shares

[test]
	path = /tmp/test
	writeable = yes
   public = yes

[reiser]
   path = /mnt/space/xfs/samba/
	writeable = yes
	public = yes

[tools]
	path = /mnt/space/xfs/samba/reiser/reiserfs/tools/
	read only = yes
	csc policy = programs
#
[xfs-acl]
	comment = XFS_ACL test directory
   path = /mnt/space/xfs/test
   writeable = yes
	nt acl support = yes
	inherit permissions = yes
#	force create mode = 777
	inherit acls = true

#
#[ext2-acl]
#   path = /samba/ext2/
#   writeable = yes
#
# this is a test-share for msdfs
# create your links with
#  ln -s msdfs:storageA\\shareA linka	
#[msdfs-share]
#   msdfs root = yes
#   path = /samba/reiser/msdfs

[mp3]
	path = /mnt/space/mp3
	read only = yes
	write list = root, administrator, @"ntusers"

[trash]
	comment = VFS recycle bin 
	path = /mnt/space/xfs/samba/muell/
	writeable = yes
	browseable = yes
	vfs object = /usr/lib/samba/vfs/recycle.so
	vfs options = recycle=.recycle

[audit]
	comment = VFS audited test directory
	path = /mnt/space/xfs/samba/muell
	vfs object = /usr/lib/samba/vfs/audit.so
	writeable = yes
	browseable = yes

[vscan-test]
	comment = VFS samba-vscan test
	path = /mnt/space/xfs/samba/vscan
	vfs object = /usr/lib/samba/vscan-fprotd.so

[msdfs]
	comment = msdfs test share
	path = /tmp/msdfs
	msdfs root = yes

[ext3]
	path = /mnt/space/test/ext3
	writeable = yes
	public = yes
