/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux localhost.localdomain 2.6.18-194.32.1.el5 #1 SMP Wed Jan 5 17:53:09 EST 2011 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Sat May 26 08:45:01 PHT 2012"
#define BUILD_ENV_SRCDIR "."
#define BUILD_ENV_BUILDDIR "."
#define BUILD_ENV_USER "liuyong"
#define BUILD_ENV_HOST "localhost.localdomain"
#define BUILD_ENV_COMPILER "/opt/buildroot-gcc342/bin/mipsel-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
